name: Generate Snake

# Controls when the action will run. This one runs on a schedule (once a day).
on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:  # Allows you to manually trigger the workflow from the GitHub Actions tab

# A job is a set of steps in a workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository's code using actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v2

      # Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure the correct Python version

      # Install required dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Assuming dependencies are listed in this file

      # Runs a custom script to generate the snake
      - name: Generate Snake
        run: |
          python generate_snake.py  # Replace this with your script for generating the snake animation

      # Commits and pushes the changes to the repository
      - name: Commit and Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Updated Snake animation" || echo "No changes to commit"
          git push
